import Head from 'next/head'
import React from 'react'

function index() {
    return (<>

        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            Log in
        </main>
    </>
    )
}

export default index